### ISSUE TITLE
Is this functional?

### ISSUE THREAD

**Issue by ghost** [Dajiban/digibytewallet-core#12]
I'm attempting to have this synced up with my coin (WeyCoin) and so far I'm only getting
```relayed orphan block```

I just need to know if this is at least functional with the DigiByte blockchain and I'm not just throwing darts in the dark here.

**Comment by gto90** [comment]
Indeed this is functional.

**Comment by ghost** [comment]
Yea, I figured. Ripped some code here and there from here, got my coin iOS wallet working as well.
